In [1]:
# import libraries

import pandas as pd
import numpy as np

In [2]:
# read in data

df = pd.read_csv('listings.csv')

In [4]:
# list of columns to keep

df.columns

Index(['id', 'name', 'summary', 'space', 'description', 'experiences_offered',
       'neighborhood_overview', 'notes', 'transit', 'thumbnail_url',
       'medium_url', 'picture_url', 'xl_picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month'],
      dtype='object')

In [5]:
# we will get rid of some columns to simplify the dataset

col = ['host_id', 'host_name', 'neighbourhood', 'calculated_host_listings_count', 'availability_365', 'notes', 'medium_url',
       'xl_picture_url', 'host_id', 'host_url',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'zipcode', 'security_deposit',
       'extra_people', 'minimum_nights',
       'calendar_updated', 
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped',
       'first_review', 'last_review',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month']

In [6]:
# drop columns
df.drop(col, axis=1, inplace=True)
df.head()

,id,name,summary,space,description,experiences_offered,neighborhood_overview,transit,thumbnail_url,picture_url,...,price,weekly_price,monthly_price,cleaning_fee,guests_included,maximum_nights,has_availability,number_of_reviews,review_scores_rating,cancellation_policy
0,241032,Stylish Queen Anne Apartment,NaN,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,NaN,NaN,NaN,https://a1.muscache.com/ac/pictures/67560560/c...,...,$85.00,NaN,NaN,NaN,2,365,t,207,95.0,moderate
1,953595,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...","Convenient bus stops are just down the block, ...",https://a0.muscache.com/ac/pictures/14409893/f...,https://a0.muscache.com/ac/pictures/14409893/f...,...,$150.00,"$1,000.00","$3,000.00",$40.00,1,90,t,43,96.0,strict
2,3308979,New Modern House-Amazing water view,New modern house built in 2013. Spectacular s...,"Our house is modern, light and fresh with a wa...",New modern house built in 2013. Spectacular s...,none,Upper Queen Anne is a charming neighborhood fu...,A bus stop is just 2 blocks away. Easy bus a...,NaN,https://a2.muscache.com/ac/pictures/b4324e0f-a...,...,$975.00,NaN,NaN,$300.00,10,30,t,20,97.0,strict
3,7421966,Queen Anne Chateau,A charming apartment that sits atop Queen Anne...,NaN,A charming apartment that sits atop Queen Anne...,none,NaN,NaN,NaN,https://a0.muscache.com/ac/pictures/94146944/6...,...,$100.00,$650.00,"$2,300.00",NaN,1,1125,t,0,NaN,flexible
4,278830,Charming craftsman 3 bdm house,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,none,We are in the beautiful neighborhood of Queen ...,The nearest public transit bus (D Line) is 2 b...,NaN,https://a1.muscache.com/ac/pictures/6120468/b0...,...,$450.00,NaN,NaN,$125.00,6,1125,t,38,92.0,strict

In [7]:
df.columns

Index(['id', 'name', 'summary', 'space', 'description', 'experiences_offered',
       'neighborhood_overview', 'transit', 'thumbnail_url', 'picture_url',
       'host_since', 'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'street', 'city', 'state', 'market', 'smart_location', 'country_code',
       'country', 'latitude', 'longitude', 'is_location_exact',
       'property_type', 'room_type', 'accommodates', 'bathrooms', 'bedrooms',
       'beds', 'bed_type', 'amenities', 'square_feet', 'price', 'weekly_price',
       'monthly_price', 'cleaning_fee', 'guests_included', 'maximum_nights',
       'has_availability', 'number_of_reviews', 'review_scores_rating',
       'cancellation_policy'],
      dtype='object')

In [8]:
# now we check for missing values
df.isnull().sum()

id                          0
name                        0
summary                   177
space                     569
description                 0
experiences_offered         0
neighborhood_overview    1032
transit                   934
thumbnail_url             320
picture_url                 0
host_since                  2
host_location               8
host_about                859
host_response_time        523
host_response_rate        523
host_acceptance_rate      773
host_is_superhost           2
host_thumbnail_url          2
host_picture_url            2
host_neighbourhood        300
street                      0
city                        0
state                       0
market                      0
smart_location              0
country_code                0
country                     0
latitude                    0
longitude                   0
is_location_exact           0
property_type               1
room_type                   0
accommodates                0
bathrooms                  16
bedrooms                    6
beds                        1
bed_type                    0
amenities                   0
square_feet              3721
price                       0
weekly_price             1809
monthly_price            2301
cleaning_fee             1030
guests_included             0
maximum_nights              0
has_availability            0
number_of_reviews           0
review_scores_rating      647
cancellation_policy         0
dtype: int64

In [12]:
df.dtypes

id                         int64
name                      object
summary                   object
space                     object
description               object
experiences_offered       object
neighborhood_overview     object
transit                   object
thumbnail_url             object
picture_url               object
host_since                object
host_location             object
host_about                object
host_response_time        object
host_response_rate        object
host_acceptance_rate      object
host_is_superhost         object
host_thumbnail_url        object
host_picture_url          object
host_neighbourhood        object
street                    object
city                      object
state                     object
market                    object
smart_location            object
country_code              object
country                   object
latitude                 float64
longitude                float64
is_location_exact         object
property_type             object
room_type                 object
accommodates               int64
bathrooms                float64
bedrooms                 float64
beds                     float64
bed_type                  object
amenities                 object
square_feet              float64
price                     object
weekly_price              object
monthly_price             object
cleaning_fee              object
guests_included            int64
maximum_nights             int64
has_availability          object
number_of_reviews          int64
review_scores_rating     float64
cancellation_policy       object
dtype: object

In [15]:
# create function that replace missing values of columns with text  'missing'

def replace_missing():
    # replace missing values of 'summary' column with text 'missing'
    df['summary'].fillna('missing', inplace=True)
    # replace missing values of 'space' column with text 'missing'
    df['space'].fillna('missing', inplace=True)
    # replace missing values of 'neighborhood_overview' column with text 'missing'
    df['neighborhood_overview'].fillna('missing', inplace=True)
    
    # replace missing values of 'transit' column with text 'missing'
    df['transit'].fillna('missing', inplace=True)
    # replace missing values of 'thumbnail_url' column with text 'missing'
    df['thumbnail_url'].fillna('missing', inplace=True)
    # replace missing values of 'host_since' column with text 'missing'
    df['host_since'].fillna('missing', inplace=True)
    # replace missing values of 'host_location' column with text 'missing'
    df['host_location'].fillna('missing', inplace=True)
    # replace missing values of 'host_about' column with text 'missing'
    df['host_about'].fillna('missing', inplace=True)
    # replace missing values of 'host_response_time' column with text 'missing'
    df['host_response_time'].fillna('missing', inplace=True)
    # replace missing values of 'host_response_rate' column with text 'missing'
    df['host_response_rate'].fillna('missing', inplace=True)
    # replace missing values of 'host_acceptance_rate' column with text 'missing'
    df['host_acceptance_rate'].fillna('missing', inplace=True)
    # replace missing values of 'host_neighbourhood' column with text 'missing'
    df['host_neighbourhood'].fillna('missing', inplace=True)
    # replace missing values of 'host_thumbnail_url' column with text 'missing'
    df['host_thumbnail_url'].fillna('missing', inplace=True)
    # replace missing values of 'host_picture_url' column with text 'missing'
    df['host_picture_url'].fillna('missing', inplace=True)
    # replace missing values of 'host_is_superhost' column with text 'missing'
    df['host_is_superhost'].fillna('missing', inplace=True)
    # replace missing values of 'host_neighbourhood' column with text 'missing'
    df['host_neighbourhood'].fillna('missing', inplace=True)
    # replace missing values of 'bathrooms' column with mode
    df['bathrooms'].fillna(df['bathrooms'].mode(), inplace=True)
    # replace missing values of 'bedrooms' column with  mode
    df['bedrooms'].fillna(df['bedrooms'].mode(), inplace=True)
    # replace missing values of 'beds' column with mode
    df['beds'].fillna(df['beds'].mode(), inplace=True)
    # replace missing values of 'square_feet' column with median
    df['square_feet'].fillna(df['square_feet'].median(), inplace=True)
    # replace missing values of 'weekly_price' column with median
    return df

In [17]:
df

,id,name,summary,space,description,experiences_offered,neighborhood_overview,transit,thumbnail_url,picture_url,...,price,weekly_price,monthly_price,cleaning_fee,guests_included,maximum_nights,has_availability,number_of_reviews,review_scores_rating,cancellation_policy
0,241032,Stylish Queen Anne Apartment,missing,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,missing,missing,missing,https://a1.muscache.com/ac/pictures/67560560/c...,...,$85.00,NaN,NaN,NaN,2,365,t,207,95.0,moderate
1,953595,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...","Convenient bus stops are just down the block, ...",https://a0.muscache.com/ac/pictures/14409893/f...,https://a0.muscache.com/ac/pictures/14409893/f...,...,$150.00,"$1,000.00","$3,000.00",$40.00,1,90,t,43,96.0,strict
2,3308979,New Modern House-Amazing water view,New modern house built in 2013. Spectacular s...,"Our house is modern, light and fresh with a wa...",New modern house built in 2013. Spectacular s...,none,Upper Queen Anne is a charming neighborhood fu...,A bus stop is just 2 blocks away. Easy bus a...,missing,https://a2.muscache.com/ac/pictures/b4324e0f-a...,...,$975.00,NaN,NaN,$300.00,10,30,t,20,97.0,strict
3,7421966,Queen Anne Chateau,A charming apartment that sits atop Queen Anne...,missing,A charming apartment that sits atop Queen Anne...,none,missing,missing,missing,https://a0.muscache.com/ac/pictures/94146944/6...,...,$100.00,$650.00,"$2,300.00",NaN,1,1125,t,0,NaN,flexible
4,278830,Charming craftsman 3 bdm house,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,none,We are in the beautiful neighborhood of Queen ...,The nearest public transit bus (D Line) is 2 b...,missing,https://a1.muscache.com/ac/pictures/6120468/b0...,...,$450.00,NaN,NaN,$125.00,6,1125,t,38,92.0,strict
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,8101950,3BR Mountain View House in Seattle,Our 3BR/2BA house boasts incredible views of t...,"Our 3BR/2BA house bright, stylish, and wheelch...",Our 3BR/2BA house boasts incredible views of t...,none,We're located near lots of family fun. Woodlan...,missing,https://a2.muscache.com/ac/pictures/103217071/...,https://a2.muscache.com/ac/pictures/103217071/...,...,$359.00,NaN,NaN,$230.00,1,1125,t,1,80.0,strict
3814,8902327,Portage Bay View!-One Bedroom Apt,800 square foot 1 bedroom basement apartment w...,This space has a great view of Portage Bay wit...,800 square foot 1 bedroom basement apartment w...,none,The neighborhood is a quiet oasis that is clos...,Uber and Car2go are good options in Seattle. T...,https://a2.muscache.com/ac/pictures/626d4b1f-6...,https://a2.muscache.com/ac/pictures/626d4b1f-6...,...,$79.00,NaN,NaN,$50.00,3,29,t,2,100.0,moderate
3815,10267360,Private apartment view of Lake WA,"Very comfortable lower unit. Quiet, charming m...",missing,"Very comfortable lower unit. Quiet, charming m...",none,missing,missing,https://a2.muscache.com/ac/pictures/a5974f04-2...,https://a2.muscache.com/ac/pictures/a5974f04-2...,...,$93.00,$450.00,NaN,$35.00,2,7,t,0,NaN,moderate
3816,9604740,Amazing View with Modern Comfort!,Cozy studio condo in the heart on Madison Park...,Fully furnished unit to accommodate most needs...,Cozy studio condo in the heart on Madison Park...,none,Madison Park offers a peaceful slow pace upsca...,Yes,https://a2.muscache.com/ac/pictures/202e4ad6-b...,https://a2.muscache.com/ac/pictures/202e4ad6-b...,...,$99.00,NaN,NaN,$45.00,1,1125,t,0,NaN,moderate
3817,10208623,Large Lakefront Apartment,"All hardwood floors, fireplace, 65"" TV with Xb...",missing,"All hardwood floors, fireplace, 65"" TV with Xb...",none,missing,missing,https://a2.muscache.com/ac/pictures/596705b3-0...,https://a2.muscache.com/ac/pictures/596705b3-0...,...,$87.00,NaN,NaN,NaN,1,1125,t,0,NaN,flexible

In [18]:
df.isnull().sum()

id                          0
name                        0
summary                     0
space                       0
description                 0
experiences_offered         0
neighborhood_overview       0
transit                     0
thumbnail_url               0
picture_url                 0
host_since                  0
host_location               0
host_about                  0
host_response_time          0
host_response_rate          0
host_acceptance_rate        0
host_is_superhost           0
host_thumbnail_url          0
host_picture_url            0
host_neighbourhood          0
street                      0
city                        0
state                       0
market                      0
smart_location              0
country_code                0
country                     0
latitude                    0
longitude                   0
is_location_exact           0
property_type               1
room_type                   0
accommodates                0
bathrooms                  16
bedrooms                    6
beds                        1
bed_type                    0
amenities                   0
square_feet                 0
price                       0
weekly_price             1809
monthly_price            2301
cleaning_fee             1030
guests_included             0
maximum_nights              0
has_availability            0
number_of_reviews           0
review_scores_rating      647
cancellation_policy         0
dtype: int64

In [20]:
# drop rows with missing values
df.dropna(inplace=True)

In [22]:
# reset index
df.reset_index(drop=True, inplace=True)

In [23]:
df

,id,name,summary,space,description,experiences_offered,neighborhood_overview,transit,thumbnail_url,picture_url,...,price,weekly_price,monthly_price,cleaning_fee,guests_included,maximum_nights,has_availability,number_of_reviews,review_scores_rating,cancellation_policy
0,953595,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...","Convenient bus stops are just down the block, ...",https://a0.muscache.com/ac/pictures/14409893/f...,https://a0.muscache.com/ac/pictures/14409893/f...,...,$150.00,"$1,000.00","$3,000.00",$40.00,1,90,t,43,96.0,strict
1,2493658,Airy + Bright Queen Anne Apartment,"Beautiful apartment in an extremely safe, quie...",What's special about this place? A beautiful r...,"Beautiful apartment in an extremely safe, quie...",none,"Queen Anne is a wonderful, truly functional vi...","Convenient bus stops are just down the block, ...",https://a2.muscache.com/ac/pictures/33003258/f...,https://a2.muscache.com/ac/pictures/33003258/f...,...,$150.00,"$1,000.00","$3,000.00",$40.00,1,365,t,32,97.0,strict
2,4454295,Upper Queen Anne Craftsman House,"Beautifully furnished, cozy 1 bedroom mid cent...",Beautiful home in an extremely walkable neighb...,"Beautifully furnished, cozy 1 bedroom mid cent...",none,I am located in the Upper Queen Anne neighborh...,"Yes, bus stops just 2-3 blocks away.",https://a0.muscache.com/ac/pictures/59566840/b...,https://a0.muscache.com/ac/pictures/59566840/b...,...,$99.00,$800.00,"$2,000.00",$150.00,1,1125,t,8,97.0,strict
3,3883392,Open Plan 2bdr/1bath in Queen Anne,Spacious apt in popular Seattle neighborhood. ...,This apartment is in a quiet and friendly city...,Spacious apt in popular Seattle neighborhood. ...,none,This neighborhood is one of Seattle's popular ...,#1 bus is one block from the house to downtown...,https://a2.muscache.com/ac/pictures/48864586/9...,https://a2.muscache.com/ac/pictures/48864586/9...,...,$245.00,"$1,575.00","$5,800.00",$95.00,1,14,t,13,98.0,moderate
4,4125779,Cozy Queen Anne Finished Basement,Relax in your own private finished basement sp...,Updated daylight basement space with queen and...,Relax in your own private finished basement sp...,none,Just a few minutes walk to many great restaura...,Metro Transit Bus #13 takes you to downtown Se...,https://a1.muscache.com/ac/pictures/52657137/d...,https://a1.muscache.com/ac/pictures/52657137/d...,...,$99.00,$568.00,"$2,029.00",$15.00,1,1125,t,11,84.0,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,6621924,Hazel Heights Hideout,An one-bedroom apartment in the top level of m...,Enter via the big back deck which has views of...,An one-bedroom apartment in the top level of m...,none,Fremont - The Center Of The Universe. This ne...,"Walking distance to Fremont, which has tons of...",https://a1.muscache.com/ac/pictures/85686578/1...,https://a1.muscache.com/ac/pictures/85686578/1...,...,$107.00,"$1,000.00","$3,633.00",$40.00,2,1125,t,21,90.0,flexible
1033,7735100,Master bedroom in Fremont,The townhouse is conveniently blocks away from...,missing,The townhouse is conveniently blocks away from...,none,missing,missing,missing,https://a1.muscache.com/ac/pictures/98338478/f...,...,$65.00,$375.00,"$1,400.00",$25.00,1,1125,t,5,95.0,moderate
1034,4524575,Comfortable Fremont Apartment,This lovely apartment is located on the lower ...,Our recently renovated apartment is perfect fo...,This lovely apartment is located on the lower ...,none,Fremont is centrally located within the city a...,"4 blocks to the #5 bus stop, providing a >20 m...",https://a1.muscache.com/ac/pictures/56811707/6...,https://a1.muscache.com/ac/pictures/56811707/6...,...,$108.00,$700.00,"$2,500.00",$45.00,2,1125,t,28,100.0,moderate
1035,6120046,Lake Veiw Cottage in Fremont,From the deck of this quaint little apartment ...,This one bedroom apartment (Hippy Shack) is de...,From the deck of this quaint little apartment ...,none,This cottage apartment is located just a few b...,This cottage apartment is located just a few b...,https://a2.muscache.com/ac/pictures/76273783/b...,https://a2.muscache.com/ac/pictures/76273783/b...,...,$120.00,$600.00,"$2,200.00",$75.00,2,30,t,10,80.0,strict
1036,262764,Fremont Farmhouse,Our 2BR/1 bath home in Fremont's most fun neig...,"1200 ft2 2BR, 1 Bath farmhouse with a large, t...",Our 2BR/1 bath home in Fremont's most fun neig...,none,We love that Fremont is so centrally located t...,We're centrally located to several bus stops t...,https://a1.muscache.com/ac/pictures/75088108/6...,https://a1.muscache.com/ac/pictures/75088108/6...,...,$154.00,"$1,120.00","$5,500.00",$85.00,4,14,t,5,92.0,strict

In [24]:
df.isnull().sum()

id                       0
name                     0
summary                  0
space                    0
description              0
experiences_offered      0
neighborhood_overview    0
transit                  0
thumbnail_url            0
picture_url              0
host_since               0
host_location            0
host_about               0
host_response_time       0
host_response_rate       0
host_acceptance_rate     0
host_is_superhost        0
host_thumbnail_url       0
host_picture_url         0
host_neighbourhood       0
street                   0
city                     0
state                    0
market                   0
smart_location           0
country_code             0
country                  0
latitude                 0
longitude                0
is_location_exact        0
property_type            0
room_type                0
accommodates             0
bathrooms                0
bedrooms                 0
beds                     0
bed_type                 0
amenities                0
square_feet              0
price                    0
weekly_price             0
monthly_price            0
cleaning_fee             0
guests_included          0
maximum_nights           0
has_availability         0
number_of_reviews        0
review_scores_rating     0
cancellation_policy      0
dtype: int64

In [25]:
# save cleaned data to csv file

df.to_csv('listings_cleaned.csv', index=False)

In [26]:
df_cleaned = pd.read_csv('listings_cleaned.csv')
df_cleaned.head()

,id,name,summary,space,description,experiences_offered,neighborhood_overview,transit,thumbnail_url,picture_url,...,price,weekly_price,monthly_price,cleaning_fee,guests_included,maximum_nights,has_availability,number_of_reviews,review_scores_rating,cancellation_policy
0,953595,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...","Convenient bus stops are just down the block, ...",https://a0.muscache.com/ac/pictures/14409893/f...,https://a0.muscache.com/ac/pictures/14409893/f...,...,$150.00,"$1,000.00","$3,000.00",$40.00,1,90,t,43,96.0,strict
1,2493658,Airy + Bright Queen Anne Apartment,"Beautiful apartment in an extremely safe, quie...",What's special about this place? A beautiful r...,"Beautiful apartment in an extremely safe, quie...",none,"Queen Anne is a wonderful, truly functional vi...","Convenient bus stops are just down the block, ...",https://a2.muscache.com/ac/pictures/33003258/f...,https://a2.muscache.com/ac/pictures/33003258/f...,...,$150.00,"$1,000.00","$3,000.00",$40.00,1,365,t,32,97.0,strict
2,4454295,Upper Queen Anne Craftsman House,"Beautifully furnished, cozy 1 bedroom mid cent...",Beautiful home in an extremely walkable neighb...,"Beautifully furnished, cozy 1 bedroom mid cent...",none,I am located in the Upper Queen Anne neighborh...,"Yes, bus stops just 2-3 blocks away.",https://a0.muscache.com/ac/pictures/59566840/b...,https://a0.muscache.com/ac/pictures/59566840/b...,...,$99.00,$800.00,"$2,000.00",$150.00,1,1125,t,8,97.0,strict
3,3883392,Open Plan 2bdr/1bath in Queen Anne,Spacious apt in popular Seattle neighborhood. ...,This apartment is in a quiet and friendly city...,Spacious apt in popular Seattle neighborhood. ...,none,This neighborhood is one of Seattle's popular ...,#1 bus is one block from the house to downtown...,https://a2.muscache.com/ac/pictures/48864586/9...,https://a2.muscache.com/ac/pictures/48864586/9...,...,$245.00,"$1,575.00","$5,800.00",$95.00,1,14,t,13,98.0,moderate
4,4125779,Cozy Queen Anne Finished Basement,Relax in your own private finished basement sp...,Updated daylight basement space with queen and...,Relax in your own private finished basement sp...,none,Just a few minutes walk to many great restaura...,Metro Transit Bus #13 takes you to downtown Se...,https://a1.muscache.com/ac/pictures/52657137/d...,https://a1.muscache.com/ac/pictures/52657137/d...,...,$99.00,$568.00,"$2,029.00",$15.00,1,1125,t,11,84.0,moderate